export const FIELDS_HEB = {
    cartodb_id: "מזהה",
    firstname: "שם פרטי",
    lastname: "שם משפחה",
    phone1: "טלפון ראשי",
    phone2: "טלפון משני",
    city: "עיר",
    street: "רחוב",
    building: "מספר בית",
    entrance: "כניסה",
    floor: "קומה",
    apartment: "מספר דירה",
    familymembers: "מספר נפשות",
    lon: "קו אורך",
    lat: "קו רוחב",
    the_geom: "גאומטריה",
    deliverstatus: "סטטוס משלוח",
    numservingsdistributed: "מנות שחולקו",
    comments: "הערות",
}

export const FIELDS_TYPE = {
    firstname: "text",
    lastname: "text",
    phone1: "text",
    phone2: "text",
    city: "text",
    street: "text",
    building: "number",
    entrance: "text",
    floor: "number",
    apartment: "number",
    familymembers: "text",
    lon: "number",
    lat: "number",
    deliverstatus: "number",
    numservingsdistributed: "number",
    comments: "text",
}